# Generated by Django 2.1.1 on 2018-09-02 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='文章标题')),
                ('summary', models.CharField(max_length=128, verbose_name='文章简介')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.Article')),
            ],
        ),
        migrations.CreateModel(
            name='BlogTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surfix', models.CharField(max_length=128)),
                ('theme', models.CharField(max_length=32, verbose_name='博客主题')),
                ('summary', models.CharField(max_length=128, verbose_name='博客简介')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.BlogTable')),
            ],
        ),
        migrations.CreateModel(
            name='CommentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('parent_comment_id', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.BlogTable')),
            ],
        ),
        migrations.CreateModel(
            name='PraiseOrBelittleArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Article')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='报障标题')),
                ('status', models.IntegerField(choices=[(1, '待处理'), (2, '处理中'), (3, '已处理')], verbose_name='处理状态')),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户姓名')),
                ('pwd', models.CharField(max_length=32, verbose_name='用户密码')),
                ('email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('img', models.ImageField(upload_to='', verbose_name='用户头像')),
                ('user_fans', models.ManyToManyField(to='repository.UserTable')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'UserTable',
            },
        ),
        migrations.AddField(
            model_name='reporttable',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_processor', to='repository.UserTable', verbose_name='报障单处理用户'),
        ),
        migrations.AddField(
            model_name='reporttable',
            name='user_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_report', to='repository.UserTable', verbose_name='报障单提交用户'),
        ),
        migrations.AddField(
            model_name='praiseorbelittlearticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.UserTable'),
        ),
        migrations.AddField(
            model_name='commenttable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.UserTable'),
        ),
        migrations.AddField(
            model_name='blogtable',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.UserTable'),
        ),
        migrations.AddField(
            model_name='article',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Classification', verbose_name='文章分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Label', verbose_name='文章标签'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.UserTable', verbose_name='文章作者'),
        ),
    ]
