# Generated by Django 2.1.1 on 2018-09-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='articledetail',
            options={'verbose_name_plural': '文章详细内容'},
        ),
        migrations.AlterModelOptions(
            name='blogtable',
            options={'verbose_name_plural': '博客表'},
        ),
        migrations.AlterModelOptions(
            name='classification',
            options={'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='commenttable',
            options={'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='praiseorbelittlearticle',
            options={'verbose_name_plural': '赞踩文章关系'},
        ),
        migrations.AlterModelOptions(
            name='reporttable',
            options={'verbose_name_plural': '报障表'},
        ),
        migrations.AlterField(
            model_name='usertable',
            name='img',
            field=models.ImageField(upload_to='statics/userphoto', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user_fans',
            field=models.ManyToManyField(blank=True, to='repository.UserTable'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
        migrations.AlterModelTable(
            name='articledetail',
            table='ArticleDetail',
        ),
        migrations.AlterModelTable(
            name='blogtable',
            table='BlogTable',
        ),
        migrations.AlterModelTable(
            name='classification',
            table='Classification',
        ),
        migrations.AlterModelTable(
            name='commenttable',
            table='CommentTable',
        ),
        migrations.AlterModelTable(
            name='label',
            table='Label',
        ),
        migrations.AlterModelTable(
            name='praiseorbelittlearticle',
            table='PraiseOrBelittleArticle',
        ),
        migrations.AlterModelTable(
            name='reporttable',
            table='ReportTable',
        ),
    ]
