# Generated by Django 2.0.6 on 2018-09-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20180920_2046'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='praiseorbelittlearticle',
            unique_together={('article', 'user')},
        ),
    ]
