# Generated by Django 2.0.6 on 2018-10-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20180928_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttable',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
