# Generated by Django 2.0.6 on 2018-10-04 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_reporttable_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttable',
            name='content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporttable',
            name='processor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_processor', to='repository.UserTable', verbose_name='报障单处理用户'),
        ),
        migrations.AlterField(
            model_name='reporttable',
            name='status',
            field=models.IntegerField(choices=[(1, '待处理'), (2, '处理中'), (3, '已处理')], default=1, verbose_name='处理状态'),
        ),
    ]
