# Generated by Django 2.0.6 on 2018-10-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_auto_20181004_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttable',
            name='solution',
            field=models.TextField(null=True),
        ),
    ]
