# Generated by Django 2.0.6 on 2018-10-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_reporttable_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttable',
            name='solution_time',
            field=models.DateTimeField(null=True),
        ),
    ]
