# Generated by Django 2.0.6 on 2018-10-12 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20181012_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='classification',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='repository.Classification', verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='label',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='repository.Label', verbose_name='文章标签'),
        ),
    ]
